name: Clippy Check

on:
  pull_request:
    paths:
      - "src/**"
      - "Cargo.lock"
  push:
    paths:
      - "src/**"
      - "Cargo.lock"

jobs:
  clippy:
    name: Run Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features